name: Java CI for Range Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Dependencies
        run: |
          mkdir -p lib
          wget -O lib/javax.servlet-api-3.0.1.jar https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar
          wget -O lib/jcommon-1.0.17.jar https://repo1.maven.org/maven2/org/jfree/jcommon/1.0.17/jcommon-1.0.17.jar

      - name: Run JUnit Tests for Range.java
        run: mvn test --fail-at-end

      - name: Build and Run Tests with Maven
        run: |
          mvn clean install
          mvn test --fail-at-end

